services:
  web:
    image: ghcr.io/fadidab98/alhakim-web:latest
    command: gunicorn --bind 0.0.0.0:8000 core.wsgi:application
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
    ports:
      - "6090:8000"  # Map host port 8001 to container port 8000
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.prod
      - DATABASE_NAME=alhakim_db
      - DATABASE_USER=alhakim_user
      - DATABASE_PASSWORD=alhakim_pass
      - DATABASE_HOST=db
      - SECRET_KEY=${SECRET_KEY}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=alhakim_db
      - POSTGRES_USER=alhakim_user
      - POSTGRES_PASSWORD=alhakim_pass


volumes:
  postgres_data: