version: '3.8'
services:
  web:
    image: ghcr.io/fadidab98/alhakim-web:latest
    pull_policy: always
    command: gunicorn --bind 0.0.0.0:8000 core.wsgi:application
    volumes:
      - ./staticfiles:/app/staticfiles
    ports:
      - "6090:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.prod
      - DATABASE_NAME=alhakim_db
      - DATABASE_USER=alhakim_user
      - DATABASE_PASSWORD=alhakim_pass
      - DATABASE_HOST=db
      - SECRET_KEY=${SECRET_KEY}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
    depends_on:
      - db
  db:
    image: postgres:13
    pull_policy: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=alhakim_db
      - POSTGRES_USER=alhakim_user
      - POSTGRES_PASSWORD=alhakim_pass
  backup:
    image: postgres:13
    volumes:
      - ./db_backups:/backups
    environment:
      - POSTGRES_DB=alhakim_db
      - POSTGRES_USER=alhakim_user
      - POSTGRES_PASSWORD=alhakim_pass
      - POSTGRES_HOST=db
    depends_on:
      - db
    command: >
      sh -c "
        while true; do
          TIMESTAMP=\$(date +%Y%m%d_%H%M%S);
          pg_dump -h \$POSTGRES_HOST -U \$POSTGRES_USER \$POSTGRES_DB > /backups/backup_\$TIMESTAMP.sql;
          ls -tp /backups/backup_*.sql | tail -n +11 | xargs -I {} rm -- {} || true;
          sleep 300;
        done
      "

volumes:
  postgres_data: