# Generated by Django 3.2 on 2023-03-22 20:52

import cloudinary.models
import common.validators.validate_file_size
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='attached_file',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[common.validators.validate_file_size.validate_file_size], verbose_name='attached_file'),
        ),
    ]
