# Generated by Django 3.2 on 2023-03-22 22:21

import cloudinary_storage.storage
import common.validators.validate_file_size
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatmessage_attached_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='attached_file',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='Chat/Files', validators=[common.validators.validate_file_size.validate_file_size]),
        ),
    ]
