# Generated by Django 3.2 on 2023-04-21 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chatmessage_attached_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ('timestamp',)},
        ),
    ]
