# Generated by Django 3.2 on 2023-03-22 20:52

import cloudinary.models
import common.validators.validate_file_size
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='cv',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[common.validators.validate_file_size.validate_file_size], verbose_name='cv'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[common.validators.validate_file_size.validate_file_size], verbose_name='profile_pic'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='syndicate_card',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[common.validators.validate_file_size.validate_file_size], verbose_name='syndicate_card'),
        ),
    ]
