# Generated by Django 3.2 on 2023-03-22 22:04

import cloudinary_storage.storage
import common.validators.validate_file_size
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20230322_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='cv',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='Doctors/CVs', validators=[common.validators.validate_file_size.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='profile_pic',
            field=models.ImageField(upload_to='Doctors/Profile-Pictures', validators=[common.validators.validate_file_size.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='syndicate_card',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='Doctors/Syndicate-Cards', validators=[common.validators.validate_file_size.validate_file_size]),
        ),
    ]
