# Generated by Django 3.2 on 2023-04-21 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20230323_0104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ('user__name_en',)},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ('user__name_en',)},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('name_en',)},
        ),
    ]
