# Generated by Django 3.2 on 2023-03-20 23:25

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('specialties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('problem', models.TextField()),
                ('symptoms', models.CharField(blank=True, max_length=225, null=True)),
                ('problem_date', models.DateField()),
                ('chronic_diseases', models.TextField(blank=True, null=True)),
                ('medicines', models.TextField(blank=True, null=True)),
                ('allergy', models.TextField(blank=True, null=True)),
                ('previous_surgeries', models.TextField(blank=True, null=True)),
                ('reply_via', models.CharField(max_length=225)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('replied', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultation_doctor', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultation_patient', to=settings.AUTH_USER_MODEL)),
                ('specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='specialties.specialty')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='cv')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='history_doctor', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='history_patient', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Consultations History',
            },
        ),
    ]
