# Generated by Django 3.2 on 2023-03-22 22:21

import cloudinary_storage.storage
import common.validators.validate_file_size
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20230322_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='Consultations/Documents', validators=[common.validators.validate_file_size.validate_file_size]),
        ),
    ]
