# Generated by Django 3.2 on 2023-04-21 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_document_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultationhistory',
            options={'ordering': ('-created',), 'verbose_name_plural': 'Consultations History'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ('consultation__created',)},
        ),
    ]
