# Generated by Django 3.2 on 2023-03-20 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=70, unique=True)),
                ('name_ar', models.CharField(max_length=70, unique=True)),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
    ]
