# Generated by Django 3.2 on 2023-04-21 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialty',
            options={'ordering': ('name_en',)},
        ),
    ]
